docs: convert markdown issue templates to issue forms
Avaiga/taipy pull request #1238
Opened 2024-04-26 18:56 UTC by Anmol-Baranwal

closes #1234 

## Changes proposed

I've added five issue forms in total and removed existing markdown templates.

I've used the existing templates as inspiration (especially the acceptance criteria).

- Documentation
- Feature Request
- Refactor Code/Feature Improvement
- Bug Report
- Other (to avoid creating blank issues) - discussion

You can see how these will [preview](https://github.com/Anmol-Baranwal/taipy/tree/issue_forms/.github/ISSUE_TEMPLATE) on my fork branch. You cannot see it while creating an issue (which I've enabled) because it's in another branch and not in the `main` branch.

If you want to see how the final issue forms will look in general, then you can check [this](https://github.com/dailydotdev/daily/issues/new?assignees=&labels=Type%3A+Feature&projects=&template=---feature-request.yaml&title=%F0%9F%A7%A9+FEATURE+REQUEST%3A++) or [this](https://github.com/rupali-codes/LinksHub/issues/new?assignees=&labels=enhancement%2Cgoal%3A+addition%2Cpriority%3A+high&projects=&template=feature_request.yml&title=%5BFeature%5D+%3Cwrite+a+small+description+here%3E). I've contributed it myself a few months back.

## Why Issue forms

- This will give you a consistent info so it will be easier to check the issue.
- Even a user with no markdown knowledge can easily fill up the form.

## Note to reviewers

1. Sections that are required are marked with `*` Asterisk.

> For instance.
![required](https://github.com/Avaiga/taipy/assets/74038190/db4c4d5e-db1e-463c-b070-850b532cb829)

2. I've also added a bit of Markdown content to improve context.

3. I've used labels of existing templates except for `discussion` and `documentation`. Let me know if any changes are necessary in that.

---

@jrobinAV 
Please suggest any necessary changes, and I will make them!

2024-04-29 06:34 UTC, florian-vuillemot commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      placeholder: ex. 3.0.1
```suggestion
      placeholder: ex. 3.1.1
```

2024-04-29 06:37 UTC, florian-vuillemot approved these changes, later dismissed

2024-04-29 06:45 UTC, Anmol-Baranwal commented
@florian-vuillemot 
I've updated the placeholder as per suggestion and marked the conversation resolved.

2024-04-30 16:57 UTC, jrobinAV submitted a review, later dismissed

2024-04-30 17:30 UTC, florian-vuillemot submitted a review, later dismissed

2024-05-03 07:45 UTC, FabienLelaquais requested changes
Mainly minor typographical change requests for better homogeneity.
Great work!

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - The more details we have, easier it would be to fix it.
```suggestion
        - The more details we have, the easier it would be to fix it. 
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - If any heading is not applicable, put `NA`
```suggestion
        - If any heading is not applicable, please set it to `NA`.
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      placeholder: Please describe the issue you experienced in detail, including any relevant information or context.
```suggestion
      placeholder: The description of the issue you experienced in detail, including any relevant information or context.
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      placeholder: Please describe the behavior that you expected to see when encountering the issue.
```suggestion
      placeholder: The description of the behavior that you expected when encountering the issue.
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        2. And/or configuration files or code:
```suggestion
        2. And/or configuration files or code
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      placeholder: Please describe the expected behavior of the problem.
```suggestion
      placeholder: The description of the expected behavior of the problem.
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - label: "Create related issue in taipy-doc for documentation and Release Notes if relevant."
```suggestion
        - label: "Create a related issue in taipy-doc for documentation and Release Notes if relevant."
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/documentation.yml
> +description: "Use this form to present your suggestions on how to improve our docs"
```suggestion
description: "Use this form to present your suggestions on how to improve our docs."
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/documentation.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      placeholder: Please enter your detailed description of the new feature request here.
```suggestion
      placeholder: A detailed description of the new feature request.
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/other.yml
> +description: Use this for any other question or issue. Please do not create blank issues
```suggestion
description: Use this for any other question or issue. Please do not create blank issues.
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/other.yml
> +      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Avaiga/taipy/blob/develop/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.co
```suggestion
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Avaiga/taipy/blob/develop/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/Avaiga/taipy/blob/develop/CONTRIBUTING.md).
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/other.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/refactor-code.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/refactor-code.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/refactor-code.yml
> +      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Avaiga/taipy/blob/develop/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.co
```suggestion
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Avaiga/taipy/blob/develop/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/Avaiga/taipy/blob/develop/CONTRIBUTING.md).
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/refactor-code.yml
> +        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)"
```suggestion
        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)."
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/refactor-code.yml
> +
```suggestion
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)"
```suggestion
        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)."
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/documentation.yml
> +        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)"
```suggestion
        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)."
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)"
```suggestion
        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)."
```

2024-05-03 07:45 UTC, FabienLelaquais commented on .github/ISSUE_TEMPLATE/other.yml
> +        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)"
```suggestion
        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)."
```

2024-05-03 15:14 UTC, Anmol-Baranwal commented
@FabienLelaquais
I've made the changes and marked the suggestions as resolved. 
Let me know if it needs any other changes!

2024-05-03 15:24 UTC, jrobinAV approved these changes, later dismissed
Thank you @Anmol-Baranwal for your help.

2024-05-10 07:15 UTC, Anmol-Baranwal commented
Hi Team, if everything is okay, please review and merge this PR.

2024-05-13 08:50 UTC, jrobinAV commented
The two other reviewers are currently on vacation. They should be back in a couple of days. I am waiting for a second approval, and once it's ok, I'll merge it. 

Thank you again.

2024-05-13 17:47 UTC, florian-vuillemot approved these changes, later dismissed

2024-05-14 11:15 UTC, Anmol-Baranwal commented
Hi Team!
Sorry for disturbing you during your vacation time. Please feel free to reply whenever you're available.

One of the tests failed due to a spelling error in `documentation.` Should I correct it, even though it will dismiss the reviews?

![image](https://github.com/Avaiga/taipy/assets/74038190/4084beee-6b6e-4773-9db4-5d6cb0f1a5bb)

Let me know your decision. I'm unsure about the issue with the other one.

Have a great day!

2024-05-14 15:05 UTC, jrobinAV commented
Hello, 

Oh, right. If you can fix it, that would be great. Thank you.

2024-05-19 19:11 UTC, Anmol-Baranwal commented
@jrobinAV 
I kind of missed it.

Anyway, I have updated it with the documentation label present in the repo.

![image](https://github.com/Avaiga/taipy/assets/74038190/430c3945-9459-4c2c-9cd3-72088e91363a)

I hope this works!

> Let me know if you want me to fix anything else or if any test is failing.

2024-05-21 08:49 UTC, jrobinAV approved these changes

2024-05-21 20:29 UTC, florian-vuillemot approved these changes
Good job thanks!

2024-05-22 07:54 UTC, FabienLelaquais approved these changes
Looks really good! Thanks!!

2024-05-22 07:56 UTC, merged