Implement fullwidth styling to FileSelector and FileDownload
Avaiga/taipy pull request #1345
Opened 2024-06-03 13:35 UTC by Satoshi-Sh

## Related Issue 
Fixed #474

##  Updates 
- Added styling files 
- Moved className to the Button component from the Label component.

## Screenshot 
![Screenshot from 2024-06-03 08-29-23](https://github.com/Avaiga/taipy/assets/73622805/2b6d7b92-5abc-42c8-b4c8-86571a0b421f)

2024-06-03 14:19 UTC, FredLL-Avaiga requested changes
I very much like the way you approach this.
I think that we cannot take the risk of breaking existing Taipy apps.

2024-06-03 14:19 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/FileDownload.tsx
> -        <label htmlFor={linkId} className={className}>
I'm afraid that moving `className` to the button will cause breaking change for the current users of Taipy.
The point of having the `className` at the top-level of the component tree of a Taipy element is to facilitate the style customization of any of the component in the element's tree.

2024-06-03 14:19 UTC, FredLL-Avaiga commented on frontend/taipy-gui/public/stylekit/controls/file_download.css
> +.taipy-file-download.fullwidth {
I propose to keep the `className` at the same level and define the style as `.taipy-file-download.fullwidth button {`

2024-06-03 14:19 UTC, FredLL-Avaiga commented on frontend/taipy-gui/public/stylekit/controls/file_selector.css
> +.taipy-file-selector.fullwidth {
idem

2024-06-03 14:19 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/FileSelector.tsx
> -        <label htmlFor={inputId} className={className}>
idem

2024-06-03 14:52 UTC, FredLL-Avaiga approved these changes
Excellent tx @Satoshi-Sh

2024-06-03 14:55 UTC, FabienLelaquais approved these changes
Neat!

2024-06-03 14:57 UTC, FredLL-Avaiga commented
@Satoshi-Sh , can I merge this ?

2024-06-03 14:59 UTC, Satoshi-Sh commented
> I'm afraid that moving className to the button will cause breaking change for the current users of Taipy.
The point of having the className at the top-level of the component tree of a Taipy element is to facilitate the style customization of any of the component in the element's tree.

Your explanation makes sense, but I have a question @FredLL-Avaiga. 

If we have the class name at the top level, we cannot style fileSelector and fileDownload by CSS as ClassName is in the label. Is it fine?

2024-06-03 15:05 UTC, FredLL-Avaiga commented
> > I'm afraid that moving className to the button will cause breaking change for the current users of Taipy.
> > The point of having the className at the top-level of the component tree of a Taipy element is to facilitate the style customization of any of the component in the element's tree.
> 
> Your explanation makes sense, but I have a question @FredLL-Avaiga.
> 
> If we have the class name at the top level, we cannot style fileSelector and fileDownload by CSS as ClassName is in the label. Is it fine?

I don't understand your point.
the className is associated to the label that is the top of the components' tree so we can access everything from there
like `.taipy-file-download button`

2024-06-03 15:08 UTC, Satoshi-Sh commented
Thanks. I got it. I will update another branch soon. @FredLL-Avaiga

2024-06-05 07:08 UTC, merged

2024-06-05 11:13 UTC, Satoshi-Sh commented
Great. Thanks for the guidance. 

Do we need to add a similar description to the indicator doc page?
![Screenshot from 2024-06-05 06-07-53](https://github.com/Avaiga/taipy/assets/73622805/46683c9e-c856-4005-b0cb-78920c1603ed)

2024-06-05 11:17 UTC, FredLL-Avaiga commented
I guess you can create a taipy-doc issue