broadcast callback on non shared variables
Avaiga/taipy pull request #1441
Opened 2024-06-21 13:57 UTC by FredLL-Avaiga

resolves #1207

renamed current `broadcast_callback` to `broadcast_callback_on_shared`

2024-06-21 15:25 UTC, FabienLelaquais commented
I think this PR is also trying to fix something that was a glitch.

@dinhlongviolin1 I need your blessing here.
This `broadcast_callback_on_shared()` to me is useless: the 'shared' state is not known by users, and should actually never been exposed.
What I expect `broadcast_callback()` to do is invoke a user-defined function, potentially with parameters, for every live state.
If then the user invokes `state.assign()` fine, so be it. But let the user decide.
What do you think?

Another important question is: does anyone see a use case for the `_on_shared` version?
Because I don't see any, and I'm willing to drop all this code...

Thanks!

2024-06-22 07:37 UTC, dinhlongviolin1 commented
> I think this PR is also trying to fix something that was a glitch.
> 
> @dinhlongviolin1 I need your blessing here. This `broadcast_callback_on_shared()` to me is useless: the 'shared' state is not known by users, and should actually never been exposed. What I expect `broadcast_callback()` to do is invoke a user-defined function, potentially with parameters, for every live state. If then the user invokes `state.assign()` fine, so be it. But let the user decide. What do you think?
> 
> Another important question is: does anyone see a use case for the `_on_shared` version? Because I don't see any, and I'm willing to drop all this code...
> 
> Thanks!

I think you are right on this one and I agree. We should drop this code as I myself don't see a use case for it. Don't remember why I add it but hopefully it wont affect anything. @FredLL-Avaiga Please help me drop it in this PR 😺

2024-06-22 08:12 UTC, FredLL-Avaiga commented
> > I think this PR is also trying to fix something that was a glitch.
> > 
> > @dinhlongviolin1 I need your blessing here. This `broadcast_callback_on_shared()` to me is useless: the 'shared' state is not known by users, and should actually never been exposed. What I expect `broadcast_callback()` to do is invoke a user-defined function, potentially with parameters, for every live state. If then the user invokes `state.assign()` fine, so be it. But let the user decide. What do you think?
> > 
> > Another important question is: does anyone see a use case for the `_on_shared` version? Because I don't see any, and I'm willing to drop all this code...
> > 
> > Thanks!
> 
> I think you are right on this one and I agree. We should drop this code as I myself don't see a use case for it. Don't remember why I add it but hopefully it wont affect anything. @FredLL-Avaiga Please help me drop it in this PR 😺 

I will drop it then

2024-06-24 07:58 UTC, FabienLelaquais requested changes
I would like to be closer to the legacy example.

2024-06-24 07:58 UTC, FabienLelaquais commented on doc/gui/examples/broadcast.py
> +Gui(page).run(debug=True)
```suggestion
Gui(page).run()
```

2024-06-24 07:58 UTC, FabienLelaquais commented on doc/gui/examples/broadcast.py
> +    broadcast_callback(state.get_gui(), update_state_var, ["button_text", button_texts[1 if thread else 0]])
The legacy code (and comment) are appropriate and should not be changed:
we want to demonstrate that a shared variable (defined as such in `Gui.add_shared_variable("button_text")`) can be propagated to all clients in a single (and simple) line of code.

2024-06-24 07:58 UTC, FabienLelaquais commented on doc/gui/examples/broadcast.py
> +def update_state_var(state: State, var_name: str, val):
```suggestion
# Invoked by the timer, for every client
def update_counter(state: State, var_name: str, val):
    # Update the variable value for this client
```

The function name indicates what it does, in the context of the invocation.

2024-06-24 07:58 UTC, FabienLelaquais commented on doc/gui/examples/broadcast.py
> +        broadcast_callback(gui, update_state_var, ["counter", counter])
```suggestion
        broadcast_callback(gui, update_counter, ["counter", counter])
```

2024-06-24 07:58 UTC, FabienLelaquais commented on frontend/taipy-gui/src/components/Taipy/PaginatedTable.tsx
> +                console.info("PTable.columns: ", (e as Error).message || e);
Because this may be read by programmers, is there any "better" information we could provide instead of the cryptic "PTable"?

2024-06-24 07:58 UTC, FabienLelaquais commented on taipy/gui/gui.py
> +    ) -> t.Dict[str, t.Any]:
👍

2024-06-24 07:58 UTC, FabienLelaquais commented on doc/gui/examples/broadcast.py
> +# using the broadcast_callback() method.
```suggestion
# using a direct assignment of the state property because the variable is declared 'shared'.
```
Should be the truth.

2024-06-24 07:58 UTC, FabienLelaquais commented on doc/gui/examples/broadcast.py
> +# The value is updated for every client using the broadcast_callback() method.
```suggestion
# The value is updated for every client in a function invoked by broadcast_callback().
```

2024-06-25 16:17 UTC, FredLL-Avaiga commented
can't approve as I am still an assignee but I would.
@FabienLelaquais I thought you wanted to add a `Gui.broadcast(var_name: str, value: t.Any)` that would call `Gui.broadcast_callback` ?

2024-06-25 16:17 UTC, FredLL-Avaiga commented
I would if you update the branch ;-)

2024-06-25 16:21 UTC, FabienLelaquais commented
> I would if you update the branch ;-)

Let me confess I completely forgot.
Thanks!

2024-06-26 07:23 UTC, FredLL-Avaiga commented on taipy/gui/gui.py
> +    def broadcast_changes(self, values: dict[str, t.Any]):
I would have used kwargs, no ?
A bit less directive maybe but much more pythonic

2024-06-26 07:23 UTC, FredLL-Avaiga commented on taipy/gui/gui.py
> +    def __broadcast_changes_fn(state: State, values: dict[str, t.Any]) -> None:
should be defined as a static method

2024-06-30 18:13 UTC, FredLL-Avaiga reviewed
👍

2024-06-30 18:32 UTC, FabienLelaquais submitted a review, later dismissed
Looking good!

2024-06-30 20:17 UTC, FabienLelaquais approved these changes, later dismissed
➕

2024-07-01 07:32 UTC, namnguyen20999 submitted a review, later dismissed
LGTM

2024-07-01 08:29 UTC, dinhlongviolin1 approved these changes, later dismissed
Amazingly done!

2024-07-01 09:37 UTC, FabienLelaquais approved these changes
👍

2024-07-01 09:38 UTC, merged