Add warnings for collision with builtin variable (#1637)
Avaiga/taipy pull request #1674
Opened 2024-08-16 16:59 UTC by dinhlongviolin1

Resolve #1637

2024-08-16 17:07 UTC, FabienLelaquais requested changes
Nice job!
Just reworded the warning message.

2024-08-16 17:07 UTC, FabienLelaquais commented on taipy/gui/utils/_evaluator.py
> +                        _warn(f"Variable '{var_name}' can't be used in taipy expression as it collides with python built-in variable")
```suggestion
                        _warn(f"Variable '{var_name}' cannot be used in Taipy expressions as its name collides with a Python built-in identifier.")
```

2024-08-16 17:49 UTC, dinhlongviolin1 commented
@FabienLelaquais Thanks for the rewording. Looks really good!

2024-08-17 09:42 UTC, namnguyen20999 approved these changes

2024-08-18 15:02 UTC, FabienLelaquais approved these changes
👍👍👍

2024-08-31 11:37 UTC, merged