multiple traces with new decimator api (#1062)
Avaiga/taipy pull request #1731
Opened 2024-08-30 17:24 UTC by dinhlongviolin1

Resolve #1062

2024-09-30 07:19 UTC, FlorianJacta commented
Is this normal that this was closed?

2024-10-05 18:12 UTC, FabienLelaquais requested changes
Please remove the two new parameters for Decimator and inherited classes.
That will be brought back the day after 4.0 is out.

2024-10-05 18:12 UTC, FabienLelaquais commented on frontend/taipy-gui/src/components/Taipy/Chart.tsx
> +                d
Wouldn't it be more readable this way?
```suggestion
                desc = {
                        xAxis: getAxis(traces, i, columns, 0),
                        yAxis: getAxis(traces, i, columns, 1),
                        zAxis: getAxis(traces, i, columns, 2),
                        chartMode: modes[i],
                }
                if (d) {
                    desc["decimator"] = d;
                }
                return desc
```

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/base.py
> +        """Decimate function.
```suggestion
        """NOT DOCUMENTED
        Decimate the dataset.
```

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/__init__.py
> +# Export the following namespace
```suggestion
# Export the following classes
```

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/base.py
> +        on_decimate: t.Optional[t.Callable] = None,
Please comment this out.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/base.py
> +        apply_decimator: t.Optional[t.Callable] = None,
Please comment this out - for the time being.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/base.py
> +            on_decimate (Optional[Callable]): an user-defined function that is executed when the decimator
Please remove the doc for these parameters - place them in a comment elsewhere so the doc doesn't mess up.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/base.py
> +        """This function is executed whenever a decimator is found during runtime.
```suggestion
        """NOT DOCUMENTED
        
        This function is executed whenever a decimator is found during runtime.
```

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/base.py
> +        """This function is executed whenever a decimator is applied to the data.
```suggestion
        """NOT DOCUMENTED
        This function is executed whenever a decimator is applied to the data.
```

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/lttb.py
> +        on_decimate: t.Optional[t.Callable] = None,
Please comment these two parameters out.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/lttb.py
> +            on_decimate (Optional[Callable]): an user-defined function that is executed when the decimator
Please move the doc for the two parameters outside this comment block.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/minmax.py
> +            on_decimate (Optional[Callable]): an user-defined function that is executed when the decimator
Please move the doc for the two parameters outside this comment block.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/rdp.py
> +            on_decimate (Optional[Callable]): an user-defined function that is executed when the decimator
Please move the doc for the two parameters outside this comment block.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/minmax.py
> +        on_decimate: t.Optional[t.Callable] = None,
Please comment these two parameters out.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/rdp.py
> +        on_decimate: t.Optional[t.Callable] = None,
Please comment these two parameters out.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/scatter_decimator.py
> +        on_decimate: t.Optional[t.Callable] = None,
Please comment these two parameters out.

2024-10-05 18:12 UTC, FabienLelaquais commented on taipy/gui/data/decimator/scatter_decimator.py
> +            on_decimate (Optional[Callable]): an user-defined function that is executed when the decimator
Please move the doc for the two parameters outside this comment block.

2024-10-07 07:55 UTC, FabienLelaquais submitted a review, later dismissed
👍

2024-10-07 10:02 UTC, FabienLelaquais approved these changes
👍

2024-10-07 10:02 UTC, merged