docs
Avaiga/taipy pull request #1820
Opened 2024-09-23 08:06 UTC by namnguyen20999

resolves https://github.com/Avaiga/taipy/issues/1819

2024-09-23 08:40 UTC, FabienLelaquais requested changes
Tell me more!

2024-09-23 08:40 UTC, FabienLelaquais commented on taipy/gui/extension/library.py
> +            properties (Dict[ElementProperty]): The dictionary of properties for this element.
Hum.
You will have to say a word about what the keys and values must be...

2024-10-03 14:48 UTC, FredLL-Avaiga commented on taipy/gui/extension/library.py
> +            properties (Dict[ElementProperty]): The dictionary containing the properties of this element, where the keys are the property names and the values are instances of ElementProperty.
that would be Dict[str, ElementProperty] ?

2024-10-03 14:54 UTC, FabienLelaquais submitted a review, later dismissed
With Fred's remark, that's fine!

2024-10-03 15:58 UTC, FabienLelaquais approved these changes
👌

2024-10-03 16:18 UTC, merged