Update INSTALLATION.md
Avaiga/taipy pull request #1870
Opened 2024-10-01 12:26 UTC by kushal34712

Made some small change will enhance the quilty of reading

2024-10-01 15:49 UTC, jrobinAV approved these changes

2024-10-02 04:56 UTC, trgiangdo requested changes

2024-10-02 04:56 UTC, trgiangdo commented on INSTALLATION.md
> +> That all that has changed is the JavaScript bundle that makes the Taipy
This is not a new sentence. Capitalize here doesn't seem right

2024-10-02 04:56 UTC, trgiangdo commented on INSTALLATION.md
> +> Try your code again.
These are all in the same sentence. Capitalize here doesn't seem right

2024-10-02 05:15 UTC, kushal34712 reviewed
i have made  changes

2024-10-02 05:17 UTC, trgiangdo commented
> i have made changes

I don't see any new commit. Did I miss something by any chance?

2024-10-02 05:24 UTC, kushal34712 commented
i have made changes but its not reflecting in the same pr do not know why

2024-10-02 05:48 UTC, closed without merging