Relax pyarrow dependency range to resolve conflict with databricks-sq…
Avaiga/taipy pull request #1988
Opened 2024-10-09 12:32 UTC by S-YED

### Detailed Description of the Changes for Issue [#1986](https://github.com/Avaiga/taipy/issues/1986)

#### Issue Summary

The issue titled "[Too much restriction on pyarrow dependency](https://github.com/Avaiga/taipy/issues/1986)" states a breaking change in dependencies from version 3.1.1 to 4.0 due to a restriction on `pyarrow`. This conflict prevents the installation of packages like `databricks-sql-connector==3.4.0`.

#### Changes Made

- **File Modified**: `setup.py` (branch: `develop`)

- **Dependency Updated**: The version range for `pyarrow` has been modified to accommodate both `Taipy` and `databricks-sql-connector` dependencies.

 - **Original Line**:

  ```python

  "arrow": ["pyarrow>=17.0.0,<18.0"],

  ```

 - **Updated Line**:

  ```python

  "arrow": ["pyarrow>=14.0.1,<18.0"],

  ```

#### Testing

- The changes were tested by attempting to install `Taipy` alongside `databricks-sql-connector==3.4.0` to ensure there are no dependency conflicts:

 ```sh

 pip install git+https://github.com/your-username/taipy.git databricks-sql-connector==3.4.0

 ```

#### Reference

This pull request addresses issue [#1986](https://github.com/Avaiga/taipy/issues/1986).

2024-10-10 17:11 UTC, FredLL-Avaiga requested changes
Good start

2024-10-10 17:11 UTC, FredLL-Avaiga commented on setup.py
> +        "arrow": ["pyarrow>=14.0.1,<18.0"],
14 seems a bit low to me
I thought that Databricks supports 16 but not 17
there is also an impact on the frontend...

2024-10-19 15:54 UTC, jrobinAV commented
This is related to databricks compatibility. Since we have a native integration with Databricks in taipy-enterprise, @toan-quach could you jump on this PR and the related issue?

2024-10-21 07:42 UTC, toan-quach commented
@S-YED thanks for your contribution!

Seems to me that the databricks team is working on a change that will remove the upper bound for dependencies => You will be able to install taipy (even with pyarrow>=17.0.0,<18.0) after their PR is merged.
https://github.com/databricks/databricks-sql-python/pull/452

However, this may take a while, so I would suggest 2 approaches:
1. @S-YED can you taipy and databricks-sql-connector by installing them separately
```
pip install git+https://github.com/your-username/taipy.git
pip install databricks-sql-connector-3.4.0
```
2. @jrobinAV we can expand pyarrow on our side to include 16.0 as the baseline as 16.0 is acceptable by `databricks-sql-connector`

2024-10-23 06:19 UTC, FredLL-Avaiga commented
I think arrow 16+ is fine (just to be sure we'll change the version in frontend/taipy-gui/package.json too)

2024-10-23 09:12 UTC, toan-quach commented
Hi @S-YED Can you help expand the version from >=16 to < 18?

2024-10-30 23:14 UTC, FredLL-Avaiga commented
Are you still working on this issue @S-YED ?
if you are not, please close this PR.

2024-10-31 14:10 UTC, jrobinAV commented on setup.py
> +        "arrow": ["pyarrow>=14.0.1,<18.0"],
```suggestion
        "arrow": ["pyarrow>=16.0,<18.0"],
```

2024-10-31 17:36 UTC, closed without merging

2024-10-31 17:44 UTC, S-YED commented
Sorry for Closing it late, I just came back to health after several days !!
Thanks for your Update!! 
@FredLL-Avaiga