#177 feat: job selector
Avaiga/taipy pull request #199
Opened 2023-06-14 15:59 UTC by pavle-avaiga

2023-06-14 17:29 UTC, FredLL-Avaiga requested changes
We also need to handle the multi-selection of the table rows (different from the checkboxes
And update the backend in the same way the selectors are working

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +        ...(selected.length > 0 && {
how does spread operator work with number= 0 ?

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const headerToolbarSx = {
useMemo

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const [selected, setSelected] = useState<readonly string[]>([]);
readonly: interesting

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const [jobRows, setJobRows] = useState<any[]>(jobs);
can't use any 
I'd have thought that the webpack eslint plugin would prevent this from happening ?

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const containerSx = { width: "100%", mb: 2 };
set as const outside the comp

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const handleClick = (event: React.MouseEvent<unknown>, name: string) => {
useCallback ?
unknown => HTMLElement ?

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +        setSelected(newSelected);
could use setSelected(sel => {...}) to avoid a dependency to the state that is modified

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const handleRequestSort = (property: string, columnIndex: number) => {
useCallback

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const [jobRows, setJobRows] = useState<any[]>(jobs);
jobs can be changed by the back-end => can't be used in useState => should be used in useEffect

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                                <IconButton onClick={() => handleDeleteJob(selected as string[])}>
this button should be disabled if one of the selected jobs cannot be cancelled

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                                <IconButton onClick={() => handleDeleteJob(selected as string[])}>
this button should be disabled if one of the selected jobs cannot be deleted

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                                <IconButton onClick={() => handleDeleteJob(selected as string[])}>
handleDeleteJob => handleCancelJobs

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                                <IconButton onClick={() => handleDeleteJob(selected as string[])}>
handleDeleteJob => handleDeleteJobs

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                    <Checkbox color="primary" checked={selectAllTrue} onChange={handleSelectAllClick} />
use a tree state checkbox to reflect the fact that some rows are checked ?

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                                onClick={() => handleRequestSort(item.id, index)}
useCallback with data-* properties

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                    onClick={(event) => handleCheckboxClick(event, id)}
useCallback

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                <ListItemText primary="Preprocess" secondary={id} />
"Preprocess" => Job name

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                <ListItemText primary="Pipeline alpha" secondary={entity} />
"Pipeline alpha" => Entity name

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const [id, submitID, entity, createdDt, status] = row;
row is [job id, job name, entity id, entity name, submit id, creation date, status]
[string, string, string, string, string, string, number]

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                    <IconButton onClick={() => handleStopJob([id])}>
useCallback

2023-06-14 17:29 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                    <IconButton onClick={() => handleDeleteJob([id])}>
useCallback

2023-06-22 15:54 UTC, FabienLelaquais requested changes
Unwanted changes here...

2023-06-22 15:54 UTC, FabienLelaquais commented on src/taipy/gui_core/GuiCoreLib.py
> +<<<<<<< HEAD
I'm.... not sure you want to commit files where merge has failed.

2023-06-22 15:54 UTC, FabienLelaquais commented on src/taipy/gui_core/GuiCoreLib.py
> +    __JOB_ACTION = "action"
That in my opinion is a big vague...
"job_action"?
Really depends on the context where it is used...

Looking at the code below, "action" is fine.
But then the sumbol (__JOB_ACTION) could certainly be renamed to __ACTION and shared

2023-06-22 15:54 UTC, FabienLelaquais commented on src/taipy/gui_core/GuiCoreLib.py
> +                "display_job_id": ElementProperty(PropertyType.boolean, True),
I... think we have user the 'show_' prefix for these sorts of things in 'scenario'.
Wouldn't it be better?

2023-06-29 08:27 UTC, FredLL-Avaiga approved these changes, later dismissed
a few comments

2023-06-29 08:27 UTC, FredLL-Avaiga commented on src/taipy/gui_core/GuiCoreLib.py
> +                "display_job_id": ElementProperty(PropertyType.boolean, True),
In scenario selector, we have show_* and display_*, I agree we should stick to one prefix (breaking change in selector :-( )

2023-06-29 08:27 UTC, FredLL-Avaiga commented on src/taipy/gui_core/GuiCoreLib.py
> +                "display_job_id": ElementProperty(PropertyType.boolean, True),
But I guess we'll fix all those in one go in another PR if you agree @FabienLelaquais ?

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/utils/types.ts
> +}
I guess these should go in JobSelector.tsx if they're only used there ?

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    defaultDisplayDate: boolean;
These properties are not dynamic, the default<property> name is not needed

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const displayDate = useDynamicProperty(props.displayDate, props.defaultDisplayDate, true);
These properties are not dynamic, they can simply be declared in the props spreading with their default value.
ie : Line 424 const { id = "", displayJobId = true, ...} = props;

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                    <IconButton onClick={() => doCancelJob([id])}>
use a data-id property and read it from the callback through the event

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                    <IconButton onClick={() => doDeleteJob([id])}>
use a data-id property and read it from the callback through the event

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                <Checkbox color="primary" checked={isItemSelected} onClick={(event) => doCheckboxClick(event, id)} />
use a data-id property and read it from the callback through the event

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +            handleCancelJobs && handleCancelJobs(id);
I don't see the need of redefining a local callback. why not use the property directly (fetching the id by data-id) ?

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +export type JobSelectorColumns = {
no need to export those types

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +            ...(selected.length > 0 && {
use a ternary operator to not spread false

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +        [selected]
this doesn't need to depend on selected if we use the setState with function
ie: setSelected((oldSelected) => ...calculate new selected);

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +            jobRows?.filter(
jobRows should never be undefined ?

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +            jobRows?.filter(
jobRows should never be undefined ?

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                                    disabled={!selectedAllowedCancelJobs || selectedAllowedCancelJobs.length == 0}
if jobRows is never undefined then selectedAllowedCancelJobs is never undefined

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                                    disabled={!selectedAllowedDeleteJobs || selectedAllowedDeleteJobs.length == 0}
if jobRows is never undefined then ...

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                                            !selectedAllowedDeleteJobs || selectedAllowedDeleteJobs.length == 0
if jobRows is never undefined then ...

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                    <Table sx={{ minWidth: 750 }} aria-labelledby="tableTitle" size="medium">
externalize sx

2023-06-29 08:27 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                            {jobRows
jobRows is never undefined

2023-06-30 07:28 UTC, FredLL-Avaiga approved these changes, later dismissed

2023-06-30 07:28 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +            return [...newSelected];
why not return newSelected ?

2023-06-30 07:28 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +                const newSelected = jobRows?.map((n) => n[0]);
jobRows will never be undefined

2023-06-30 07:28 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const selectedAllowedCancelJobs = useMemo(
this should be a boolean
and false if one of the selected row is not cancellable
use jobRows.some()

2023-06-30 07:28 UTC, FredLL-Avaiga commented on gui/src/JobSelector.tsx
> +    const selectedAllowedDeleteJobs = useMemo(
this should be a boolean
and false if one of the selected row is not deletable

2023-06-30 18:05 UTC, FredLL-Avaiga approved these changes

2023-07-03 08:01 UTC, FabienLelaquais approved these changes
👌

2023-07-03 08:02 UTC, merged