added group_by property
Avaiga/taipy pull request #2007
Opened 2024-10-10 09:27 UTC by eleensmathew

I made some changes to add group_by property. Please check and let me know where I'm going wrong? All kinds of pointers are appreciated.

2024-10-10 11:48 UTC, jrobinAV commented
Can you create unit tests of the new method `get_grouped_scenario_list(entities, group_by)`?
Unit tests help to:

- make the PR easy to review
- improve the readability and maintainability of the code
- document how a method should be used
- avoid future bugs or regressions

Thank you.

2024-10-10 17:20 UTC, FredLL-Avaiga requested changes
not finished yet :-)

2024-10-10 17:20 UTC, FredLL-Avaiga commented on taipy/gui_core/_context.py
> +        group_by: t.Optional[str],
How do you specify that parameter ?
I think you need to add it as an external property in _GuiCoreLib.py

2024-10-10 17:21 UTC, eleensmathew commented on taipy/gui_core/_context.py
> +        group_by: t.Optional[str],
Ok thanks for pointing that out. Will make the changes.

2024-10-24 07:41 UTC, FredLL-Avaiga commented
@eleensmathew Are you still working on this ?
Can you address the remaining questions and failed checks ?
If you're not, can you close this PR ?

2024-10-24 09:05 UTC, eleensmathew commented
Feel free to assign it to someone else

2024-10-24 09:28 UTC, FredLL-Avaiga commented
> Feel free to assign it to someone else

We can unassign the issue no problem, but we don't want hanging PRs. So please close it if you're not planning on working on the subject anymore.

2024-10-24 14:30 UTC, closed without merging