[BUGFIX] Implement Focus Out Event Handling for Input Controls
Avaiga/taipy pull request #2035
Opened 2024-10-12 16:08 UTC by nagarajpandith

This commit adds an onBlur event handler to the input control in Taipy GUI, ensuring that input validation is triggered when the user focuses out of the input field. 

### Changes:
- Added `handleBlur` function to dispatch the update action when the input field loses focus.
- Ensured that all input types (text, number, date) are affected by this change.

### Acceptance Criteria:
- Input controls should now validate on focus out, equivalent to pressing the Enter key.
- All new code is unit tested with a code coverage of at least 90%.
<img width="338" alt="Screenshot 2024-10-12 at 9 37 33 PM" src="https://github.com/user-attachments/assets/55f0325e-428e-4eb2-a98d-362a66e87369">

2024-10-15 16:02 UTC, FredLL-Avaiga requested changes
Don't see no tests

2024-10-15 16:02 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/Input.tsx
> +        const val = e.target.value;
you need to stop the timer if any

2024-10-15 16:02 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/Input.tsx
> +        const val = e.target.value;
use currentTarget

2024-10-18 12:10 UTC, UTK-a-RSH approved these changes

2024-10-18 12:33 UTC, FredLL-Avaiga commented
@UTK-a-RSH Thanks for *not* approving PR :-)

2024-10-24 07:36 UTC, FredLL-Avaiga commented
Hi @nagarajpandith, are you still working on this ?
If you are, please, answer the questions
If you are not, please close this PR

2024-10-30 15:35 UTC, closed without merging