Update INSTALLATION.md
Avaiga/taipy pull request #2049
Opened 2024-10-14 11:41 UTC by UTSAVS26

I have made some changes in `INSTALLATION.md` to make it more readable.

2024-10-14 12:24 UTC, UTSAVS26 commented
Hi @jrobinAV , can you please review my PR and tell what changes i need to do or it is final?

2024-10-14 16:09 UTC, AlexandreSajus reviewed
![image](https://github.com/user-attachments/assets/f6b30c5f-65e8-4c00-83d0-3c6a7c6fe0e5)

2024-10-14 16:25 UTC, UTSAVS26 commented
> ![image](https://github.com/user-attachments/assets/f6b30c5f-65e8-4c00-83d0-3c6a7c6fe0e5)
> 

Thank you, i have corrected my mistake. Sorry for the trouble.

2024-10-15 02:53 UTC, UTSAVS26 commented
@FabienLelaquais @AlexandreSajus @FlorianJacta @jrobinAV please review it. Thank you

2024-10-15 07:42 UTC, jrobinAV requested changes
We keep lines with less than 100 characters as much as possible for readability and maintainability.

2024-10-15 07:42 UTC, jrobinAV commented on INSTALLATION.md
> +Taipy can be installed in various ways depending on your needs. If you aim to modify the code or contribute to its development, refer to the [source installation](#installing-for-development) section
```suggestion
Taipy can be installed in various ways depending on your needs. If you aim to modify the code
or contribute to its development, refer to the 
[source installation](#installing-for-development) section. Ensure that you have Python 3.9 or
above installed on your system.
```

2024-10-15 07:42 UTC, jrobinAV commented on INSTALLATION.md
> +The easiest way to install Taipy is through the [PyPI software repository](https://pypi.org/project/taipy/). You can do this by running the following command:
```suggestion
The easiest way to install Taipy is through the
[PyPI software repository](https://pypi.org/project/taipy/). You can do this by running the
following command:
```

2024-10-15 08:04 UTC, UTSAVS26 commented
> We keep lines with less than 100 characters as much as possible for readability and maintainability.

@jrobinAV made necessary changes as requested, please review. Thank you for your time.

2024-10-15 10:24 UTC, jrobinAV approved these changes

2024-10-15 10:25 UTC, merged

2024-10-15 10:26 UTC, UTSAVS26 commented
@jrobinAV Thank you for approving my PR. I am going to contribute more like this in repo.

thank you once again.

2024-10-15 10:28 UTC, UTSAVS26 commented
If possible can you add `Hacktoberfest` and `hacktoberfest-accepted` lebel if possible for you, thank you :)

2024-10-15 10:56 UTC, jrobinAV commented
Sorry, only the PRs that refer to an `hacktoberfest` labeled issue are counting for the hacktoberfest event.

But there are [many of them](https://github.com/Avaiga/taipy/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) not resolved yet, and we are adding some new `hacktoberfest` issues every day.

2024-10-15 13:44 UTC, UTSAVS26 commented
> Sorry, only the PRs that refer to an `hacktoberfest` labeled issue are counting for the hacktoberfest event.
> 
> But there are [many of them](https://github.com/Avaiga/taipy/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) not resolved yet, and we are adding some new `hacktoberfest` issues every day. 

So can I create new issues for Hacktoberfest if I want to?

2024-10-15 14:00 UTC, jrobinAV commented
1. You can create a new issue on the taipy repository. 

2. The maintainer team must review the issue and decide if it is accepted and if we want to implement it as part of the product. 

3. If the issue is accepted, the maintainer team decides whether it is open for external contribution (labeled "good first issue" or "help wanted"), whether it is a candidate for hacktoberfest event (labeled "hacktoberfest"), or if it must be implemented by an internal developer (labeled "staff only").

2024-10-15 14:15 UTC, UTSAVS26 commented
Okie @jrobinAV thanks for your clarification.