Update DateRange.tsx
Avaiga/taipy pull request #2050
Opened 2024-10-14 12:03 UTC by Aryam2121

timeStep Prop: Control the rounding by passing a timeStep prop (e.g., 15 for 15-minute intervals).
Testing: Implement unit tests outside of this file to validate the functionality and edge cases of rounding behavior.
UI Considerations: The layout remains responsive and adjusts to the presence or absence of withTime.solve issue #2034

2024-10-17 08:23 UTC, FredLL-Avaiga requested changes
this is not finished I guess ?

2024-10-17 08:23 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/DateRange.tsx
> +const roundToStep = (date: Date | null, step: number | undefined): Date | null => {
Should go in a dateUtils.ts so that we can reuse it in dateSelector.tsx and timeSelector.tsx ...

2024-10-17 08:23 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/DateRange.tsx
> +    return setMinutes(setHours(date, date.getHours()), roundedMinutes);
what happens if step = 40 and current min = 50 ?
roundedMinutes would be 80 
How does DateFns handles this ?

2024-10-17 08:23 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/DateRange.tsx
> -                    {props.children}
Why ?

2024-10-17 08:23 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/DateRange.tsx
> -const getRangeDateTime = (
Why ?

2024-10-17 08:23 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/DateRange.tsx
> -    const module = useModule();
Why ?

2024-10-22 08:13 UTC, FredLL-Avaiga commented
Are you still working on this @Aryam2121 ?
if you do, update your branch, resolve the conflicts and answer the questions, tx.
if not please close the PR.

2024-10-30 23:09 UTC, FredLL-Avaiga commented
> Are you still working on this @Aryam2121 ? if you do, update your branch, resolve the conflicts and answer the questions, tx. if not please close the PR.

WIthout a reply from you @Aryam2121, we'll have to close this PR ...

2024-10-31 06:06 UTC, Aryam2121 commented
I am updated already

2024-10-31 08:12 UTC, FredLL-Avaiga commented
can you resolve the conflicts and fix the failing checks ?

2024-11-13 09:06 UTC, FredLL-Avaiga commented
no activity, closing

2024-11-13 09:06 UTC, closed without merging