fix #1814 update_content for debug off
Avaiga/taipy pull request #2106
Opened 2024-10-20 22:57 UTC by rohitdash08

This PR fix #1814

**Description:**
Fixes issue with update_content() behavior inconsistency in debug vs. non-debug modes.

**Summary of Changes:**

1. Introduced a queue-based system (UpdateQueue) to batch and control the frequency of updates for partials.

2. Implemented two batch intervals:
STREAM_MODE_BATCH_INTERVAL for smooth updates during streaming (0.05s).
STANDARD_BATCH_INTERVAL for non-streaming updates (0.2s).

3. Added thread safety using locks to ensure consistent updates and prevent race conditions.

4. Created a new method _process_updates() to handle queued updates and apply only the most recent change.

5. Added a force_update() method for forced updates when necessary.

**Impact:**
This fix addresses the "chunky" updates observed when debug mode is off, ensuring smoother and more consistent content updates across all modes.

2024-10-21 13:05 UTC, FredLL-Avaiga requested changes

2024-10-21 13:05 UTC, FredLL-Avaiga commented on taipy/gui/partial.py
> +            queue.updates.setdefault(state._gui, []).append((current_time, self.__copy(content)))
Could there be more than one instance of Gui ?

2024-10-21 13:05 UTC, FredLL-Avaiga commented on taipy/gui/partial.py
> +            queue.updates.setdefault(state._gui, []).append((current_time, self.__copy(content)))
I suppose you meant `get_state_id(state)` instead of `state._gui` ?

2024-10-21 13:06 UTC, FredLL-Avaiga commented
can you update your branch and fix the checks ?

2024-10-21 15:48 UTC, FredLL-Avaiga commented
I've updated your branch

2024-10-21 17:07 UTC, rohitdash08 commented on taipy/gui/partial.py
> +            queue.updates.setdefault(state._gui, []).append((current_time, self.__copy(content)))
@FredLL-Avaiga,  Yes, there could be more than one instance of Gui, I have made the changes please let me know if anything else is required?

2024-10-21 17:18 UTC, FredLL-Avaiga requested changes
Can you write some test so that we can understand where you're getting to ?

2024-10-21 17:18 UTC, FredLL-Avaiga commented on taipy/gui/partial.py
> +    def update_content(self, state: State, content: t.Union[str, "Page"], stream_mode: bool = False):
make stream_mode optional ? t.Optional[bool] = False

2024-10-21 17:18 UTC, FredLL-Avaiga commented on taipy/gui/partial.py
> +        gui_id = get_state_id(state)
that would be `state_id` but not gui_id

2024-10-21 17:18 UTC, FredLL-Avaiga commented on taipy/gui/partial.py
> +            gui_updates = t.list[t.Tuple[float, Partial]] = queue.updates.get(gui_id, [])
I suppose `gui_updates = t.list[t.Tuple[float, Partial]] =` => `gui_updates: t.list[t.Tuple[float, Partial]] =` ?

2024-10-21 17:18 UTC, FredLL-Avaiga commented on taipy/gui/partial.py
> +            queue.updates.setdefault(state._gui, []).append((current_time, self.__copy(content)))
`state._gui` => gui_id ?

2024-10-21 17:18 UTC, FredLL-Avaiga commented on taipy/gui/partial.py
> +    def _process_updates(self, state: State, gui_id: str):
no need for gui_id as it is calculated from state ...

2024-10-30 10:25 UTC, closed without merging

2024-10-30 12:15 UTC, rohitdash08 commented
Hey @FredLL-Avaiga, can you please review this one the issue seems to be fixed locally can you check once?
#2187

2024-10-30 12:49 UTC, FredLL-Avaiga commented
I don't see any tests
Why is this closed?

2024-10-30 13:18 UTC, rohitdash08 commented
Due to some issue, I had to forked it again so I have created a new PR #2187 .
You can find the tests here.