demo for resizing test
Avaiga/taipy pull request #2327
Opened 2024-12-12 17:25 UTC by namnguyen20999

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

## How to reproduce the issue

_Please replace this line with instructions on how to reproduce the issue or test the feature._

## Other branches or releases that this needs to be backported
_Describe which projects this change will impact and that needs to be backported._

## Checklist
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Does this solution meet the acceptance criteria of the related issue?
- [ ] Is the related issue checklist completed?
- [ ] Does this PR adds unit tests for the developed code? If not, why?
- [ ] End-to-End tests have been added or updated?
- [ ] Was the documentation updated, or a dedicated issue for documentation created? (If applicable)
- [ ] Is the release notes updated? (If applicable)

2024-12-16 07:02 UTC, FabienLelaquais requested changes
Looking good.
A few details though

2024-12-16 07:02 UTC, FabienLelaquais commented on tests/gui/e2e/test_resizing.py
> +    page_md = """
```suggestion
    page_md = "<|{data}|chart|type=bar|x=Year|y=%|>"
```

2024-12-16 07:02 UTC, FabienLelaquais commented on tests/gui/e2e/test_resizing.py
> +    assert box_after['width'] > box_before['width']
```suggestion
    assert box_after["width"] > box_before["width"]
```

2024-12-16 07:02 UTC, FabienLelaquais commented on taipy/gui/viselements.json
> +                        "default_value": "20vw",
```suggestion
                        "default_value": "\"20vw\"",
```

2024-12-16 07:02 UTC, FabienLelaquais commented on taipy/gui/viselements.json
> +                        "default_value": "20vh",
```suggestion
                        "default_value": "\"20vh\"",
```

2024-12-16 07:02 UTC, FabienLelaquais commented on frontend/taipy-gui/src/components/Taipy/Metric.tsx
> +const defaultLayout = { margin: { l: 50, r: 50, t: 50, b: 50 } } as Partial<Layout>;
Why such large margins?

2024-12-16 07:02 UTC, FabienLelaquais commented on frontend/taipy-gui/src/components/Taipy/Metric.tsx
> +    width: "20vw",
May be a little comment here and next line indicating this impact viselements.json - in order to remember in the future

2024-12-16 07:09 UTC, namnguyen20999 commented on frontend/taipy-gui/src/components/Taipy/Metric.tsx
> +const defaultLayout = { margin: { l: 50, r: 50, t: 50, b: 50 } } as Partial<Layout>;
If the margin is set to 0, the metric’s number overflows outside the container, making it invisible. Adjusting it as shown ensures a better appearance when the default width and height are 20vw and 20vh, respectively. If the user want different margin then they can use the "layout" property to override it

2024-12-17 07:35 UTC, FabienLelaquais approved these changes
👌

2024-12-17 07:35 UTC, FabienLelaquais commented on frontend/taipy-gui/src/components/Taipy/Metric.tsx
> +const defaultLayout = { margin: { l: 50, r: 50, t: 50, b: 50 } } as Partial<Layout>;
👍

2024-12-17 08:41 UTC, merged