Backports for 4.0.2
Avaiga/taipy pull request #2336
Opened 2024-12-16 09:47 UTC by FabienLelaquais

Backport to 4.0 of Taipy GUI issues
#2212 ([PR#2250](https://github.com/Avaiga/taipy/pull/2256)),
#2242 ([PR#2250](https://github.com/Avaiga/taipy/pull/2250)),
#2281 ([PR#2315](https://github.com/Avaiga/taipy/pull/2315)),
#2286 ([PR#2300](https://github.com/Avaiga/taipy/pull/2300)),
#2302 ([PR#2314](https://github.com/Avaiga/taipy/pull/2314)), and
#2305 ([PR#2313](https://github.com/Avaiga/taipy/pull/2313)).

2024-12-16 10:05 UTC, FredLL-Avaiga approved these changes, later dismissed

2024-12-16 10:05 UTC, FredLL-Avaiga commented on frontend/taipy-gui/package.json
> +  "version": "4.0.2",
there are more package.json files to change I believe

2024-12-16 10:05 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/Chart.tsx
> +const getDataKey = (columns: Record<string, ColumnDesc>, decimators?: string[]): [string[], string] => {
I think there's an issue with columns being undefined here
I fixed it locally but did not push it to develop yet

2024-12-16 14:33 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/Chart.tsx
> +const getDataKey = (columns: Record<string, ColumnDesc>, decimators?: string[]): [string[], string] => {
```py
const getDataKey = (columns?: Record<string, ColumnDesc>, decimators?: string[]): [string[], string] => {
    const backCols = columns ? Object.values(columns).map((col) => col.dfid) : [];
    return [backCols, backCols.join("-") + (decimators ? `--${decimators.join("")}` : "")];
};
```

2024-12-17 07:58 UTC, FabienLelaquais commented on frontend/taipy-gui/package.json
> +  "version": "4.0.2",
👍

2024-12-17 07:58 UTC, FabienLelaquais commented on frontend/taipy-gui/src/components/Taipy/Chart.tsx
> +const getDataKey = (columns: Record<string, ColumnDesc>, decimators?: string[]): [string[], string] => {
In there.

2024-12-17 08:07 UTC, FredLL-Avaiga requested changes

2024-12-17 08:07 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/Taipy/Chart.tsx
> +const getDataKey = (columns: Record<string, ColumnDesc>, decimators?: string[]): [string[], string] => {
we need this

2024-12-17 08:32 UTC, FredLL-Avaiga approved these changes
👍

2024-12-17 08:34 UTC, merged