feature/#397 scenario duplication
Avaiga/taipy pull request #2373
Opened 2024-12-27 07:16 UTC by toan-quach

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Implementation of a new feature to duplicate a scenario.
+
Make the various reason messages consistent.

## Related Tickets & Documents
#397

2025-01-15 12:18 UTC, jrobinAV requested changes

2025-01-15 12:18 UTC, jrobinAV commented on tests/core/scenario/test_scenario_manager.py
> +    assert old_scenario.id != new_scenario.id
We don't want to change the scenario (even in memory). we want to create a new one.

THe following must be tested.

```suggestion
    assert old_scenario.id != new_scenario.id
    assert old_scenario.id == scenario.id
```

Unfortunately, this means we need to change the implementation.

2025-01-15 13:10 UTC, toan-quach commented on tests/core/scenario/test_scenario_manager.py
> +    assert old_scenario.id != new_scenario.id
fixed! :D

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +        cloned_scenario.id = cloned_scenario_id
```suggestion
        cloned_scenario.id = cloned_scenario._new_id(cloned_scenario.config_id)
```

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/data/_data_manager.py
We should implement a can_duplicate method, returning reasons, just like we have a can_create method.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/data/_data_manager.py
> +        cloned_dn._clone_data()
If the data node has a cycle scope, and if the new scenario is from the same cycle, then we want to share the same data node between scenarios.
If the scope is global it always already exists, and we also want to share the existing one.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +        return ""
Do we want to differentiate the cases where the initial path is generated by Taipy or provided by the user?
I believe it would be better. If it is Taipy generated, we can just replace the old id by the new one. otherwise, adding a prefix or a suffix as you did make sense.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +            cloned_additional_data_nodes.add(_data_manager._clone(data_node, None, cloned_scenario_id))
Duplicating data nodes should depend on its scope.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +        cloned_scenario._tasks = cloned_tasks
Duplicating tasks should depend on minimal scope of inputs and outputs data nodes.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/task/_task_manager.py
> +        outputs = [data_manager._clone(o, cycle_id, scenario_id) for o in cloned_task.output.values()]
THis should depend on the scope of the data nodes.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/data/_data_manager.py
> +    def _clone(
I would rename _clone to _duplicate

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +    def _clone(cls, scenario: Scenario) -> Scenario:
I would rename _clone method to _duplicate as it does not return another instance of the same object. It returns a similar object with a few differences (ids, sub-entities' ids, paths, etc...)

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
We should implement a can_duplicate method, returning reasons, just like we have a can_create method.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +    def _clone(cls, scenario: Scenario) -> Scenario:
We should accept an optional name and an optional date in the method signature. It does not change much for the name but it does for the creation date. This has an impact on the potential cycle as the new scenario might be on a different cycle.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +    def _clone(cls, scenario: Scenario) -> Scenario:
According to the issue, we should also pass an optional list of data nodes or data node IDs. Without any list; we should copy all the data. If the list is provided, only the files of the data nodes in the list should be copied.

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/task/_task_manager.py
> +    def _clone(cls, task: Task, cycle_id: Optional[CycleId] = None, scenario_id: Optional[ScenarioId] = None) -> Task:
I would rename _clone method to _duplicate as it does not return another instance of the same object. It returns a similar object with a few differences (ids, sub-entities' ids, paths, etc...)

2025-01-15 14:38 UTC, jrobinAV commented on taipy/core/data/csv.py
> +        return new_data_path
I would move that outside the data node, to put it in the data_manager.
Just like we handle the parent_ids and the owner_id in the manager, I would set the path property in the manager as well (still retrieving the value from a fileDatanodeMixing method).
This is debatable, though...

2025-01-16 06:28 UTC, toan-quach commented on taipy/core/scenario/_scenario_manager.py
> +    def _clone(cls, scenario: Scenario) -> Scenario:
hm? I can understand the name, but the creation date?

2025-01-16 07:46 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +    def _clone(cls, scenario: Scenario) -> Scenario:
Let's say I have a January scenario I am happy with. I want to start with a duplicate of this one to compute my February scenario. So beginning of February I duplicate my January scenario passing the current date so the new scenario is in the February cycle. 

Does it make sense for you? And @FlorianJacta any opinion on that?

2025-01-16 08:23 UTC, FlorianJacta commented on taipy/core/scenario/_scenario_manager.py
> +    def _clone(cls, scenario: Scenario) -> Scenario:
I agree; duplication for me was not about the creation date. Your use case is a real use case from CFM

2025-01-16 08:28 UTC, toan-quach commented on taipy/core/data/csv.py
> +        return new_data_path
well this is specific for file DNs only, if we put it in the data manager, we're grouping it with other types of DNs like Sql or mongo, I don't think it's a good idea

2025-01-16 08:28 UTC, toan-quach commented on taipy/core/scenario/_scenario_manager.py
> +    def _clone(cls, scenario: Scenario) -> Scenario:
I'll leave it as the next step for now

2025-01-21 14:24 UTC, jrobinAV commented on taipy/core/_repository/_filesystem_repository.py
> +        if match := [(c, p) for c, p in config_and_owner_ids if (c if isinstance(c, str) else c.id) in filepath.name]:
How can c be a str here?
I don't get this change.

2025-01-21 14:24 UTC, jrobinAV commented on taipy/core/_repository/_filesystem_repository.py
> +        # breakpoint()
To be removed

2025-01-21 14:24 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +            self.__logger.error(f"Error uploading `{up_path.name}` to data " f"node `{self.id}`:")  # type: ignore[attr-defined]
Please check your automatic formatter as this line is over 120 chars. Please revert the change.

2025-01-21 14:24 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +    def _duplicate(cls, scenario: Scenario, creation_date: Optional[datetime] = None) -> Scenario:
what about passing an optional name for the new scenario and an optional list of data nodes to duplicate? Do you plan to do it in another PR?

2025-01-22 02:54 UTC, toan-quach commented on taipy/core/_repository/_filesystem_repository.py
> +        if match := [(c, p) for c, p in config_and_owner_ids if (c if isinstance(c, str) else c.id) in filepath.name]:
I want to be able to pass config.id as well as the config. As when duplicating, I'm also looking for existing entities based on the scope + owner.id + config, but if so, we will need to find the config again, while in the entity, we already have config_id and we only need config_id anyway so minor change here is easier and cleaner than looking for the config object from config_id

2025-01-22 02:55 UTC, toan-quach commented on taipy/core/scenario/_scenario_manager.py
> +    def _duplicate(cls, scenario: Scenario, creation_date: Optional[datetime] = None) -> Scenario:
yep I'm planning to do it in another PR to make it cleaner as the current one is already rather complicated

2025-01-22 08:26 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +    def _duplicate(cls, scenario: Scenario, creation_date: Optional[datetime] = None) -> Scenario:
ALl right. I let you create the potential issue if you need it.

2025-01-22 08:28 UTC, jrobinAV commented on taipy/core/_repository/_filesystem_repository.py
> +        if match := [(c, p) for c, p in config_and_owner_ids if (c if isinstance(c, str) else c.id) in filepath.name]:
I don't get all the details, but you seem to have deeply thought about it. That's enough for me. 😆 
Good to me.

2025-01-22 08:30 UTC, jrobinAV submitted a review, later dismissed

2025-01-22 13:53 UTC, jrobinAV approved these changes, later dismissed

2025-01-23 10:22 UTC, trgiangdo reviewed
I believe there are still a few areas in the code that can be improve

2025-01-23 10:22 UTC, trgiangdo commented on taipy/core/data/excel.py
> +        return new_data_path
Is this repetitive?
Can we put this in the parent `_FileDataNodeMixin` class and override it when necessary?

2025-01-23 10:22 UTC, trgiangdo commented on taipy/core/data/_file_datanode_mixin.py
> +            new_base_path = os.path.join(folder_path, f"{self.__TAIPY_CLONED_PREFIX}_{id}_{base_name}")
I have 2 questions.
What would be the new file name if a data node is duplicated twice?
Similarly, if a duplicated data node is duplicated (dn -> duplicated_dn -> duplicated duplicated_dn)?

2025-01-23 10:22 UTC, trgiangdo commented on taipy/core/scenario/_scenario_manager.py
> +        # TODO: update sequences
This is not handled yet right?

2025-01-23 10:22 UTC, trgiangdo commented on taipy/core/data/_data_manager.py
> +    def _can_duplicate(cls, dn: DataNode) -> ReasonCollection:
Should we also add a Reason here when the datanode is not a file-based one?

2025-01-23 10:22 UTC, trgiangdo commented on tests/core/test_taipy.py
> +        dn_config = Config.configure_in_memory_data_node("dn", 10)
If an `InMemory` data node is duplicated, won't it raise the `NotImplementedError`?

2025-01-23 11:41 UTC, toan-quach commented on taipy/core/scenario/_scenario_manager.py
> +        # TODO: update sequences
ah yep, I'm not sure about it at the moment as if we want to duplicate a sequence, we either:
- duplicate a scenario (which is weird)
- duplicate the sequence and store it within the same scenario (this is also weird as not sure about its benefit)

2025-01-23 11:43 UTC, toan-quach commented on taipy/core/data/_file_datanode_mixin.py
> +            new_base_path = os.path.join(folder_path, f"{self.__TAIPY_CLONED_PREFIX}_{id}_{base_name}")
yep so take `example.csv` as the file name, after you first duplicate the dn, it will create a new file `TAIPY_CLONED_new_dn_id_example.csv`. But if you want to duplicate this newly duplicated dn, another file will be created with the name pattern being `TAIPY_CLONED_another_new_dn_id_example.csv`. The `TAIPY_CLONED` prefix won't be repeated.

2025-01-23 11:44 UTC, toan-quach commented on tests/core/test_taipy.py
> +        dn_config = Config.configure_in_memory_data_node("dn", 10)
yep, as we're currently focusing on file-based DN, I decided to ignore other cases and let `NotImplementedError` be raised

2025-01-23 11:45 UTC, toan-quach commented on taipy/core/data/_data_manager.py
> +    def _can_duplicate(cls, dn: DataNode) -> ReasonCollection:
well eventually we want to be able to duplicate all DNs so it will only be applicable for now and will be removed later. So I think it won't bring much value for now as we will change it later anyway.

2025-01-23 11:47 UTC, toan-quach commented on taipy/core/data/excel.py
> +        return new_data_path
hmmm I think it's a yes and no answer. The `self._properties` attribute doesn't exist in `_FileDataNodeMixin`, but since ExcelDN, etc. are implementing `_FileDataNodeMixin`, it can access it. But the syntax feels off for me, and since `_FileDataNodeMixin` is a Mixin, I'm not comfortable putting `self._properties` in it. (I understand that we do have similar things for `def path(self, value)` (setter) in `_FileDataNodeMixin`, but I'm still not sure if it's the best way to do it).

2025-01-23 13:26 UTC, trgiangdo commented on taipy/core/data/excel.py
> +        return new_data_path
I understand your point. However, other methods in the Mixin class doesn't seem to fit as well.

I think we did discuss this once. @jrobinAV Let us know what you think about this

2025-01-23 13:27 UTC, trgiangdo commented on taipy/core/data/_file_datanode_mixin.py
> +            new_base_path = os.path.join(folder_path, f"{self.__TAIPY_CLONED_PREFIX}_{id}_{base_name}")
I see. So what about duplicating a data node twice?

2025-01-23 13:28 UTC, trgiangdo commented on tests/core/test_taipy.py
> +        dn_config = Config.configure_in_memory_data_node("dn", 10)
I think we should return a Reason, not raise an exception though.

2025-01-24 02:41 UTC, toan-quach commented on tests/core/test_taipy.py
> +        dn_config = Config.configure_in_memory_data_node("dn", 10)
ah yep, agree. But I left`NotImplementedError` there as we will fill in for other data nodes eventually. By then, Reason will become outdated. So to avoid confusion in later date, I just raise `NotImplementedError` for now :D

2025-01-24 02:43 UTC, toan-quach commented on taipy/core/data/_file_datanode_mixin.py
> +            new_base_path = os.path.join(folder_path, f"{self.__TAIPY_CLONED_PREFIX}_{id}_{base_name}")
then we will have `TAIPY_CLONED_dn_duplicated_id_1_example.csv` for the 1st dn, and for 2nd dn, we will have `TAIPY_CLONED_dn_duplicated_id_2_example.csv`

2025-01-27 15:05 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +            new_base_path = os.path.join(folder_path, f"{self.__TAIPY_CLONED_PREFIX}_{id}_{base_name}")
I believe having both the prefix `TAIPY_CLONED` and the unique ID in the name is not necessary. If we can make the file name unique with the new ID, what is the purpose of keeping the prefix? We can probably propose something slightly better differentiating the case where the file name is generated by taipy or if it is provided by the user.

If the file of the initial dn is generated (`dn.is_generated`), we can simply generate a new name for the duplicate with the same function (`dn._build_path`). Otherwise, we can use your proposal without the prefix: `{new_id}_{base_name}`.

What do you think?

2025-01-27 15:05 UTC, jrobinAV commented on tests/core/data/test_csv_data_node.py
> +    def test_clone_data_file(self):
rename to `test_duplicate_data_file`

2025-01-27 15:05 UTC, jrobinAV commented on taipy/core/scenario/_scenario_manager.py
> +        # TODO: update sequences
I don't understand.

In the new scenario, we want to create a new sequence made of the duplicates tasks.

2025-01-27 15:06 UTC, jrobinAV commented on taipy/core/data/excel.py
> +        return new_data_path
Yes, this is debatable. I would personally do the same as the path setter for consistency.

2025-02-05 09:44 UTC, toan-quach commented on taipy/core/data/_file_datanode_mixin.py
> +            new_base_path = os.path.join(folder_path, f"{self.__TAIPY_CLONED_PREFIX}_{id}_{base_name}")
Well because I think the prefix will make the naming clear as to what it is, just the id is fine but we will have to state clearly in the doc that this is what we generated. While they can understand it just from the prefix without doc.

2025-02-05 11:22 UTC, jrobinAV submitted a review, later dismissed

2025-02-05 11:22 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +                )  # type: ignore[attr-defined]
The type ignore should apply to the `self.id` code.

2025-02-05 11:22 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +    def _duplicate_data_file(self, id: str) -> Optional[str]:
```suggestion
    def _duplicate_file(self, id: str) -> Optional[str]:
```

2025-02-05 11:22 UTC, jrobinAV commented on tests/core/data/test_csv_data_node.py
> +    def test_duplicate_data_file(self):
```suggestion
    def test_duplicate_data(self):
```

2025-02-05 11:22 UTC, jrobinAV commented on tests/core/data/test_csv_data_node.py
> +        assert filecmp.cmp(path, new_file_path)
```suggestion
        assert filecmp.cmp(old_path, new_file_path)
```

2025-02-05 11:22 UTC, jrobinAV commented on tests/core/data/test_csv_data_node.py
> +        assert filecmp.cmp(path, new_file_path)
What about adding an explicit assert to ensure the new path is correct?
```suggestion
        assert new_file_path == "data_sample/TAIPY_DUPLICATED_example.csv"
        assert filecmp.cmp(path, new_file_path)
```

2025-02-10 08:46 UTC, jrobinAV submitted a review, later dismissed
I believe I know what's bugging me. 
It's a matter of responsibility. 

In short, I believe the data duplication should not be the responsibility of the data node.
In my mind, the data node class only knows itself and does not have a global view of all the data nodes, or scenarios. Duplicating data should be the responsibility of classes that have an overview of the situation. Either the managers or new classes dedicated to the data duplication.

Give me some time to propose something else

2025-02-10 08:46 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +            self.__logger.error(f"Error uploading `{up_path.name}` to data " f"node `{self.id}`:")  # type: ignore[attr-defined]
```suggestion
            self.__logger.error(f"Error uploading `{up_path.name}` to data "
                                f"node `{self.id}`:")  # type: ignore[attr-defined]
```

2025-02-25 16:46 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +        )
```suggestion
       self.track_edit(timestamp=datetime.now(),  # type: ignore[attr-defined]
                        editor_id=editor_id,
                        comment=comment, **kwargs)
```

2025-02-25 16:48 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +       self.track_edit(timestamp=datetime.now(),  # type: ignore[attr-defined]
```suggestion
        self.track_edit(timestamp=datetime.now(),  # type: ignore[attr-defined]
```

2025-02-28 09:04 UTC, toan-quach commented on taipy/core/data/_file_datanode_mixin.py
> +
I think we can add it back right after setting all the values to the `self._properties` here, the new `_entity_owner` should be the new data node id I suppose

2025-03-03 20:43 UTC, jrobinAV approved these changes, later dismissed
Self approved

2025-03-04 14:26 UTC, trgiangdo reviewed
This is much cleaner.

I have a few minor suggestions

2025-03-04 14:26 UTC, trgiangdo commented on taipy/core/data/_data_duplicator.py
> +        if isinstance(self.src, _FileDataNodeMixin):
```suggestion
        if self.can_duplicate():
```

2025-03-04 14:26 UTC, trgiangdo commented on taipy/core/data/_data_duplicator.py
> +                raise NotImplementedError("Source and destination data nodes must have the same storage type.")
I don't think we should raise the `NotImplementedError` here, since this doesn't make sense for implementation.

Maybe a custom exception like `InvalidDestinationDataNode`, or the existing `InvalidDataNodeType`

2025-03-04 14:26 UTC, trgiangdo commented on taipy/core/data/_data_duplicator.py
> +            raise NotImplementedError("Data node type not supported yet.")
```suggestion
            raise NotImplementedError(f"Data node type '{self.src.storage_type()}' is not supported for duplication yet.")
```

2025-03-04 14:26 UTC, trgiangdo commented on taipy/core/data/_file_datanode_mixin.py
> +            folder_path, base_name = os.path.split(self._path)
I don't get this. Look like we have a white space in the path.

Shouldn't we split by the `os.path.sep`?

2025-03-05 13:12 UTC, jrobinAV commented on taipy/core/data/_data_duplicator.py
> +                raise NotImplementedError("Source and destination data nodes must have the same storage type.")
You are right.

2025-03-05 13:30 UTC, jrobinAV submitted a review, later dismissed

2025-03-05 13:30 UTC, jrobinAV commented on taipy/core/data/_file_datanode_mixin.py
> +            folder_path, base_name = os.path.split(self._path)
That's what it does. Its a path split, not a string split.

2025-03-05 13:32 UTC, jrobinAV approved these changes, later dismissed

2025-03-05 14:59 UTC, trgiangdo commented on taipy/core/data/_file_datanode_mixin.py
> +            folder_path, base_name = os.path.split(self._path)
Oh that's right. Perfect then :D

2025-03-05 14:59 UTC, trgiangdo submitted a review, later dismissed
LGTM

2025-03-05 16:33 UTC, merged