init commit
Avaiga/taipy pull request #2375
Opened 2024-12-30 09:50 UTC by namnguyen20999

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

## How to reproduce the issue

_Please replace this line with instructions on how to reproduce the issue or test the feature._

## Other branches or releases that this needs to be backported
_Describe which projects this change will impact and that needs to be backported._

## Checklist
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] This solution meets the acceptance criteria of the related issue.
- [ ] The related issue checklist is completed.
- [ ] This PR adds unit tests for the developed code. If not, why?
- [ ] End-to-End tests have been added or updated. If not, why?
- [ ] The documentation has been updated, or a dedicated issue created. (If applicable)
- [ ] The release notes have been updated? (If applicable)

2025-01-02 10:14 UTC, FredLL-Avaiga requested changes

2025-01-02 10:14 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/pages/TaipyRendered.tsx
> +const setScript = (id: string, scriptPaths: string[]): void => {
Can we not use helmet for this ?

2025-01-03 09:31 UTC, namnguyen20999 commented on frontend/taipy-gui/src/components/pages/TaipyRendered.tsx
> +const setScript = (id: string, scriptPaths: string[]): void => {
I've put the script outside of the Helmet

2025-01-03 15:48 UTC, FredLL-Avaiga requested changes

2025-01-03 15:48 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/pages/TaipyRendered.tsx
> +                if (v.tag === "script") {
I don't get this. What does it bring ?

2025-01-06 10:18 UTC, FredLL-Avaiga requested changes, later dismissed
so no way to use Helmet ?

2025-01-06 10:18 UTC, FredLL-Avaiga commented on frontend/taipy-gui/src/components/pages/TaipyRendered.tsx
> +    console.log(head)
to be removed

2025-01-06 10:41 UTC, namnguyen20999 commented on frontend/taipy-gui/src/components/pages/TaipyRendered.tsx
> +    console.log(head)
removed

2025-01-06 10:41 UTC, namnguyen20999 commented on frontend/taipy-gui/src/components/pages/TaipyRendered.tsx
> +    console.log(head)
I don't see any case of using Helmet here

2025-01-09 08:37 UTC, FabienLelaquais requested changes
We can discuss that anytime.

2025-01-09 08:37 UTC, FabienLelaquais commented on taipy/gui/_page.py
> +        self._script_paths: t.Optional[t.Union[str, Path, t.List[t.Union[str, Path]]]] = None
Is there a situation where a script would not be 'a path to a script' (like an inline script)?
If not I would certainly rename this to '_scripts' for clarity.

2025-01-09 08:37 UTC, FabienLelaquais commented on taipy/gui/page.py
> +        self.script_paths(kwargs.get("script_paths", None))
```suggestion
        self.scripts(kwargs.get("scripts", None))
```
(see above)

2025-01-09 08:37 UTC, FabienLelaquais commented on taipy/gui/page.py
> +    def script_paths(self, script_paths: t.Optional[t.Union[str, Path, t.List[t.Union[str, Path]]]]) -> Page:
I though we agreed that the Page constructor would have an additional 'scripts' parameter (just like 'style').
What is this API?

2025-01-09 08:37 UTC, FabienLelaquais commented on taipy/gui/page.py
> +    def _get_script_paths(self):
I don't think you actually need that.

2025-01-09 08:37 UTC, FabienLelaquais commented on taipy/gui/server.py
> +                "scriptPaths": script_paths
```suggestion
                "scripts": scripts
```

2025-01-09 09:26 UTC, namnguyen20999 commented on taipy/gui/_page.py
> +        self._script_paths: t.Optional[t.Union[str, Path, t.List[t.Union[str, Path]]]] = None
The reason is that I want to keep it aligned with `script_paths` in the Gui class.

2025-01-10 08:34 UTC, FabienLelaquais approved these changes, later dismissed
👌

2025-01-10 08:34 UTC, FabienLelaquais commented on taipy/gui/gui.py
> +                page._rendered_jsx, page._script_paths if page._script_paths is not None else [], page._style if page._style is not None else "", page._head, context #noqa: E501
I though this '#' would need to be prefixed an additional space char

2025-01-10 09:00 UTC, namnguyen20999 commented on taipy/gui/gui.py
> +                page._rendered_jsx, page._script_paths if page._script_paths is not None else [], page._style if page._style is not None else "", page._head, context #noqa: E501
space added

2025-01-13 08:56 UTC, FabienLelaquais approved these changes
👌

2025-01-13 08:57 UTC, merged