feature/#485 migrate job status update for scenario status to using submission entity
Avaiga/taipy pull request #603
Opened 2023-12-13 08:29 UTC by toan-quach

# Changes:
- Removed updating scenario status based on job
- Added updating scenario status using Submission entity status
- Removed unneeded code

2023-12-13 08:47 UTC, FredLL-Avaiga requested changes
I was hoping that we could wait for the addition of user data to the submit before changing this whole thing.
This would break the job_selector component

2023-12-13 08:47 UTC, FredLL-Avaiga commented on taipy/gui_core/_context.py
> +                    self.client_submission[sub_id] = sub_details.set_submission(new_status)
the parameter should be a submission

2023-12-13 08:47 UTC, FredLL-Avaiga commented on taipy/gui_core/_context.py
> +            _warn(f"Job ({submission_id}) is not available", e)
Job => Submission

2023-12-13 08:47 UTC, FredLL-Avaiga commented on taipy/gui_core/_context.py
> +                            self.client_submission[submission_entity.submit_entity_id] = _SubmissionDetails(
is job.submit_id != submisssion_entity.id ?

2023-12-13 08:47 UTC, FredLL-Avaiga commented on taipy/gui_core/_context.py
> -    def get_jobs_list(self):
this is used by the job_selector component

2023-12-13 08:47 UTC, FredLL-Avaiga commented on taipy/gui_core/_context.py
> -        elif event.entity_type == EventEntityType.JOB:
this is used by the job_selector component

2023-12-14 16:30 UTC, FredLL-Avaiga submitted a review, later dismissed

2023-12-14 17:45 UTC, FredLL-Avaiga approved these changes

2023-12-18 15:18 UTC, jrobinAV approved these changes
There are not so much tests on the gui_core context, and we remove the only code that was tested... Too bad. 🤣🤣🤣 

It looks good to me.

2023-12-18 15:18 UTC, jrobinAV commented on taipy/gui_core/_context.py
> +# TODO remove when Submission is supported by Core API
Noted!

https://github.com/Avaiga/taipy/issues/612

2023-12-19 14:11 UTC, merged