Feature/#411 - Raise error if config_id is an entity attribute
Avaiga/taipy pull request #620
Opened 2023-12-19 06:07 UTC by trgiangdo

https://github.com/Avaiga/taipy/issues/411

2023-12-19 12:14 UTC, jrobinAV requested changes
I believe this PR is promising but does not cover the use cases. It prevents a `data_node_config` from being named like a data node attribute, a `scenario_config` from being named like a scenario attribute, etc. 
But actually we want to prevent a `data_node_config` from having the name of a scenario attribute.

1. For instance, a data_node_config cannot be named "tags" because we want to be able to do 'scenario.<data_node_config_name>.read()' and if <data_node_config_name> is "tags", there is a conflict with the 'tags' property.
2. Another question, why is it a pb to name a scenario "tags", or a data_node "skippable". I cannot see any conflict.

2023-12-19 12:14 UTC, jrobinAV commented on taipy/core/data/data_node.py
> +
I believe it was on purpose not to have the properties.

Both `config_id` and owner_id must not be editable. You cannot change the config_id of a data node at runtime.

2023-12-19 12:14 UTC, jrobinAV commented on taipy/core/scenario/scenario.py
> +
It must not be editable.

2023-12-19 12:14 UTC, jrobinAV commented on taipy/core/task/task.py
> +
Same here. They must not be editable.

2023-12-19 12:17 UTC, trgiangdo commented on taipy/core/data/data_node.py
> +
It was editable before since the `config_id` was public. To avoid it to be editable, we can remove the setter

2023-12-19 12:22 UTC, jrobinAV commented on taipy/core/data/data_node.py
> +
yes, indeed.

2023-12-20 07:13 UTC, trgiangdo commented
In the latest commits:
- The id of a `DataNodeConfig` should not be named as a Task or Scenario attribute
- The id of a `TaskConfig` should not be named as a Scenario attribute

2023-12-20 15:31 UTC, jrobinAV approved these changes

2023-12-21 08:31 UTC, merged